### ISSUE TITLE
Exception: miniprot exited with non-zero exit code: -9

### ISSUE THREAD

**Issue by cbortoluzzi** [huangnengCSU/compleasm#10]
Hi, 

I am trying to run compleasm on a genome assembly after installing it in conda. However, I keep getting this message:

Exception: miniprot exited with non-zero exit code: -9

What should I do about it? I get the same error even after manually installing compleasm and specifying the path to miniprot. 

Best, Chiara

**Comment by huangnengCSU** [comment]
Hi Chiara,

Could you show the command you ran and what are the input files?

Neng

**Comment by cbortoluzzi** [comment]
Hi Neng, 

this is the command I used: 

compleasm run -a assembly.fasta -o test_output -t 10 -L busco_lineages/mammalia_odb10/ -l mammalia -m busco --miniprot_execute_path /path/to/miniprot/miniprot --hmmsearch_execute_path /path/to/compleasm/hmmer-3.4/src/hmmsearch

The input is just an assembly in FASTA format. The lineage was previously downloaded from here: https://busco-data.ezlab.org/v5/data/

Chiara

**Comment by huangnengCSU** [comment]
Hi Chiara,

I think this is caused by that the lineage from BUSCO can not directly used in compleasm. I suggest you run the command:
 ```compleasm run -a assembly.fasta -o test_output -t 10 -l mammalia```. It will download the lineage automatically. If the computing node does not have access to network, you can run ```compleasm download -L $library_path mammalia``` to download the lineage manually and then run the command ```compleasm run -a assembly.fasta -o test_output -t 10 -L $library_path -l mammalia```

Neng

**Comment by cbortoluzzi** [comment]
Hi Neng, 

I did run your commands (first compleasm download and then compleasm run), but I still get the same error. Not sure why...

Chiara

**Comment by huangnengCSU** [comment]
Hi Chiara,

Could you share with me a demo (part of assembly.fasta) that failed? Also, could you share the compleasm log? Following is an example of the output log.
<img width="1398" alt="image" src="https://github.com/huangnengCSU/compleasm/assets/28866823/ac48ab34-a712-4c90-8c8f-186f5484bc3f">

Neng

**Comment by cbortoluzzi** [comment]
Hi Neng, 

so here is the output log:

Searching for miniprot in the path where compleasm.py is located
Searching for miniprot in the current execution path
Searching for miniprot in $PATH
Searching for hmmsearch in the path where compleasm.py is located
Searching for hmmsearch in the current execution path
Searching for hmmsearch in $PATH
miniprot execute command:
 /cluster/work/pausch/cbortoluzzi/softwares/miniconda3/envs/compleasm/bin/miniprot
lineage: mammalia_odb10
[M::mp_ntseq_read@6.805*0.97] read 2835773169 bases in 402 contigs
[M::mp_idx_build@6.805*0.97] 22154892 blocks
Traceback (most recent call last):
  File "/cluster/work/pausch/cbortoluzzi/softwares/miniconda3/envs/compleasm/bin/compleasm", line 10, in <module>
    sys.exit(main())
  File "/cluster/work/pausch/cbortoluzzi/softwares/miniconda3/envs/compleasm/lib/python3.7/site-packages/compleasm.py", line 2534, in main
    args.func(args)
  File "/cluster/work/pausch/cbortoluzzi/softwares/miniconda3/envs/compleasm/lib/python3.7/site-packages/compleasm.py", line 2426, in run
    mr.Run()
  File "/cluster/work/pausch/cbortoluzzi/softwares/miniconda3/envs/compleasm/lib/python3.7/site-packages/compleasm.py", line 2120, in Run
    alignment_output_dir)
  File "/cluster/work/pausch/cbortoluzzi/softwares/miniconda3/envs/compleasm/lib/python3.7/site-packages/compleasm.py", line 304, in run_miniprot
    raise Exception("miniprot exited with non-zero exit code: {}".format(exitcode))
Exception: miniprot exited with non-zero exit code: -9


And here is a part of the assembly.fasta:

>1
ACGAGGCCACGTCTGGAATGTCGTCGTGAGACCGGCCTCATCCTGAGGTGCGACCCGAAG
GTCGGGAACCCCTTCCAGACAAAGCAGGGGAGTCGACCCTCCTGTGGAGACCAGGAGGGT
AGAAGGGGCTCAGAGGAAGTGGTGCCGGAAAACCTCGGTGTTCCTCTCCAGGGAGACCGG
GATGACTGGGACCTTTGTGGGGACGCATCAAGGGTGCCAAGTACCGTTTCGACCTCCAAT
TCCTCACGTGGGACTTCTCCTGAGACGCTGTAGCGGGAAAGGGCTTCATCTTGCGATGAC
GGGGGAACCACGTGGTTTTTCTCGAGTTGCGGCAGGATTCTCGAGTTACGACGGGGAATT
CAGGATGCCTCTTGTGTTGGCCCAGGGAAGTCCAATCTTCCATTCGAGTTGCGGAGGAAA
GCTGGGGATTGCTCTCGAGTGTCTGCAGGGCCAATAGACCTCATCTAGGCTTGTGTCCAG
AAGCCAATGTTCCTCTCCAGGGGCGACCGGCATCTCCGGGTTGCATTCCAGACGCAACCG
GGGAGACAGGCATTCATCTCGAGTGGAAGCAAAGAACCCCGCTCTGCTCTCGAATCGCGA
CGGGTATCTCTTGGGGCTCACTGGGTGGACTAAAGGGAGTCAAGCCTCCTGAGGCGTTTG
GAGAGAGGTCGCGAGATTGGCCTCTAGGCCATGCAGGAGACGAAGGCCCTCATCTCCGCG
ATGACGGGGGAGTCTCGGGGTGGTTCTCGAGCGGCGGCCCCAGGGTGCGGTTTCTCACGA
GGTATGACGGCGAGGTCAGTGAGCCTCTCGTGGGGCGCCAGGGAAGTCGGGTCTCCATGC
GAGTGGCGAGGGGGAGCGCGTCATTGCTCTCGAGTCGTGGTAGCGGAATCTGGCATCGAG
ACGTGTTGAAGAAGGTCTCTCGAGGTCTTTCTCGGGTTAAGGCAGGAAACCCTGGCTTCC
CTCGACTTGTGCAGGTGACCTCAGGGGGCTTCTCATGGTGGCTCTGAGAAGTCCGGGAAA
CTGGAGGTGGGAGGGGCCTCTCGGGACTCCACGGGGTTTGGTGCATTGGAAGAGGGCCTC
ATCTCCAGTTGAGGCAGGAACCTCAGGGTTCCTCTGATTTCAGACTCCGATCGCAGGGTC

**Comment by huangnengCSU** [comment]
Could you run miniprot individually as ```miniprot --trans -u -I --outs=0.95 --gff -t $threads $assembly $protein > output.gff```. Here ```$protein``` is the file in the folder ```mammalia_odb10``` named ```refseq_db.faa.gz```. And what will happen?

Neng

**Comment by cbortoluzzi** [comment]
If I run miniprot individually, I don't get any error message...that's weird, isn't it?

**Comment by huangnengCSU** [comment]
Could you list the file information (file name, size, etc.) under the output folder of compleasm? And there may be two solutions:
    1. run miniprot individually and use ```compleasm analyze -g $output.gff -o $out_dir -l $lineage -t $threads``` to perform the assessment.
    2. remove everything that compleasm generated and re-run ```compleasm run```.

**Comment by cbortoluzzi** [comment]
I think I will go for option 1 because that's the one working for me :). Thanks a lot Neng for all your help! You can close this issue.
