### ISSUE TITLE
Documentation of summary output

### ISSUE THREAD

**Issue by pgonzale60** [huangnengCSU/compleasm#11]
Hello @huangnengCSU,

Thank you for this great and fast tool. Could you please provide a description of the output files. I realise they are very similar to those of BUSCO but differ in slight ways. For example, I noticed a category labeled "I" in the summary output but is not part of BUSCO output. Looking at the code it seems to stand for "interspaced_genes".

I was hoping you could clarify the meaning and interpretation of this category, as it was not discussed in the paper:

What exactly do "interspaced_genes" refer to?
Why was this category included in the output?
How should we interpret the presence/absence of these genes?

Adding documentation on this category would help users accurately understand the "compleasm" results. Please let me know if any additional details would be helpful. Thank you for developing this useful tool!

Best regards,
Pablo

**Comment by huangnengCSU** [comment]
Hi @pgonzale60 

Thank you for the question and suggestion. We separated fragmented genes into two categories. "F" means a gene that only a portion is present in the assembly and the rest cannot be aligned. "I" represents a gene that can not be fully aligned to a single position in the assembly. A section of the gene aligns to one position while the remaining aligns to another position in the assembly.

BTW I will add more detail information about the output results.

Thank you!
Neng

**Comment by pgonzale60** [comment]
Hi Neng,

Thank you for the clarification. The distinction between "F" and "I" now makes sense to me. I appreciate you taking the time to explain it, and I look forward to the additional details you'll be adding to the output results. This will undoubtedly be helpful for other users as well.

Keep up the great work on the project.

All the best,
Pablo
