### ISSUE TITLE
Error miniprot 

### ISSUE THREAD

**Issue by rlibouba** [huangnengCSU/compleasm#14]
Hello, 

When I tried to leave the sub-module miniprit, I got this error:

`Traceback (most recent call last):
  File "/home/rlibouba/.conda/envs/mamba/envs/compleasm/bin/compleasm", line 10, in <module>
    sys.exit(main())
  File "/home/rlibouba/.conda/envs/mamba/envs/compleasm/lib/python3.7/site-packages/compleasm.py", line 2534, in main
    args.func(args)
  File "/home/rlibouba/.conda/envs/mamba/envs/compleasm/lib/python3.7/site-packages/compleasm.py", line 2348, in miniprot
    miniprot_execute_path = MiniprotRunner.search_miniprot()
AttributeError: type object 'MiniprotRunner' has no attribute 'search_miniprot'`

I installed compleams using conda and followed the instructions on your github.
Do you know what the problem is? 
Thank you very much.
Have a nice day, 
Romane

**Comment by huangnengCSU** [comment]
Hi @rlibouba, 

I have fix the bug in the code. Could you clone the source code and re-run it in the existing compleasm env?

e.g.
```
git clone https://github.com/huangnengCSU/compleasm.git
python compleasm.py miniprot -a genome.fasta -p protein.faa -o output_dir -t 8
```
Thanks!

**Comment by rlibouba** [comment]
Hello @huangnengCSU , 

Thank you for your help. By cloning the git, it worked. 
Would it be possible to open a release to update the conda package, please? 

Have a nice day, 
Romane

**Comment by huangnengCSU** [comment]
Hi @rlibouba,

I have released the new version and updated bioconda package.

Best,
Neng
