### ISSUE TITLE
mammalian database

### ISSUE THREAD

**Issue by sanjin725** [huangnengCSU/compleasm#21]
Does Compleasm not support busco's mammalian database? Although I define -l Mammalian, he still downloads and uses 2019 eukaryota,-L also cant use.

**Comment by huangnengCSU** [comment]
Hi,
Could you show the command? We tested human data with mammalian before.

**Comment by sanjin725** [comment]
> Hi, Could you show the command? We tested human data with mammalian before.
thanks for reply
my set: compleasm run -a hifi.fasta -o output_dir -l mammalia -L mypath/mammalia_odb10 .
Later on, I also reported an error when running against the Eukaryota database.

**Comment by huangnengCSU** [comment]
The command seems fine. How did you get the database? And could you show the error information?
