### ISSUE TITLE
version info

### ISSUE THREAD

**Issue by jbh-cas** [huangnengCSU/compleasm#22]
Thanks for the great tool and also for keeping a separate BUSCO compatible full_table_busco_format.tsv along with the compleasm full_table.tsv. I have several scripts that depend on that format, so it is very useful to have.

Also thanks for integrating compleasm into the etp BRAKER 3.0.7 analysis.  Looking forward to using that and seeing how it  enhances etp mode results.

As more changes are added to compleasm, I find that I am missing having a --version and/or -v option as a compleasm.py command line option to see what version of the program is being run. I know it is in _version.py but it would be nice if this could be reported by the program. Could just be added to the -h --help output if it was in a predictable location in the output, but still seems like having a separate --version command is useful even if it is added to the help screen too.

Thanks again, best,
jim henderson

**Comment by huangnengCSU** [comment]
Thanks for the suggestion.

**Comment by jbh-cas** [comment]
Thank you. Works great.
