### ISSUE TITLE
md5 hash is incorrect: 8f6c62320cd30f8017af530cbb099536 while 8f6c62320cd30f8017af530cbb099536  file_versions.tsv expected

### ISSUE THREAD

**Issue by dukecomeback** [huangnengCSU/compleasm#23]
Hi,

I installed compleasm using conda. It run into error message:

_md5 hash is incorrect: 8f6c62320cd30f8017af530cbb099536 while 8f6c62320cd30f8017af530cbb099536  file_versions.tsv expected
deleting corrupted file mb_downloads/file_versions.tsv
Unable to download necessary files_

Any suggestions please?

**Comment by huangnengCSU** [comment]
@dukecomeback Hi,

Recently the BUSCO file formats have changed which caused this problem. I have solved the problem in the latest version of compleasm. Please reinstall compleasm using conda.

**Comment by dukecomeback** [comment]
The new version works! Thank you.
