### ISSUE TITLE
Can't read the genome sequence

### ISSUE THREAD

**Issue by zhidaobuzhidao** [huangnengCSU/compleasm#26]
Hi,
When evaluating genomes, are there any requirements for genome size or individual sequence length?
I am now evaluating a 25G genome, but the run log shows no sequence read.
As follows

[M::mp_ntseq_read@5.445*1.00] read 0 bases in 0 contigs
[M::mp_idx_build@5.445*1.00] 0 blocks
[M::mp_idx_build@5.445*1.00] collected syncmers
[M::mp_idx_build@5.503*1.00] 0 kmer-block pairs

How can I solve this problem?
Looking forward to reply!

**Comment by huangnengCSU** [comment]
Hi, 
This should be the bug of miniprot aligning proteins to large chromosome (maybe greater than 2Gb) [#59](https://github.com/lh3/miniprot/issues/59#issue-2174191112). We need to wait for miniprot to fix this problem. 

A sub-optimal solution is separating the large chromosome into several parts and each part has a size less than 1.5Gb. Then evaluate the assembly with new chromosome. This may have a little impact on the evaluation result.

**Comment by zhidaobuzhidao** [comment]
Thanks for your reply and suggestions！
It is no problem to cut chromosomes into contig to run.
