### ISSUE TITLE
What's the difference between compleasm run and busco --miniprot?

### ISSUE THREAD

**Issue by juanjo255** [huangnengCSU/compleasm#27]
Hello,
I'm assessing genome completeness from a de novo genome assembly. When I run BUSCO --miniprot and compleasm there is a slight different between the results. Perhaps Do you know what's the reason for this?
dataset eurotiales_odb10
**Busco result:**
C:95.8%[S:95.4%,D:0.4%],F:0.3%,M:3.9%,n:4191,E:35.9%
4012    Complete BUSCOs (C)    (of which 1441 contain internal stop codons)               |
3997    Complete and single-copy BUSCOs (S)                                               |
15    Complete and duplicated BUSCOs (D)                                                  |
11    Fragmented BUSCOs (F)                                                               |
168    Missing BUSCOs (M)                                                                 |
4191    Total BUSCO groups searched                                                       |
command used:  busco -f --miniprot -c 32 -l eurotiales_odb10 -m genome -i assembly.fasta -o out_busco_miniprot

**Compleasm result:**
S:97.18%, 4073
D:0.12%, 5
F:0.12%, 5
I:0.00%, 0
M:2.58%, 108
N:4191
command used: compleasm run -t 32 -l eurotiales_odb10 -a assembly.fasta -o out_compleasm

Thank you very much for the help,

Juan

**Comment by huangnengCSU** [comment]
Hi Juan,

When implementing compleasm, we did not directly apply miniprot to busco, but almost re-implemented the evaluation based on the general logic of busco. So there maybe some detail we haven't notice. Currently I could not tell which detail resulting in the difference. But it is interesting to compare the difference between the compleasm and busco --miniprot. I will dig into them as well.
