### ISSUE TITLE
how to evaluate more than one genome assembly

### ISSUE THREAD

**Issue by Jerry-bioinformatics** [huangnengCSU/compleasm#29]
Hi, 
I see that this tools runs 10 times faster than BUSCO, but how can I evaluate more than one genome assembly in only one command line? I tried to add twice the "-a" options for two genome assemblies, but the result in summary.txt only output one.
The command line and results are as follows.
[command line] compleasm run -a Assembly-primary.fasta -a Assembly-alternate.fasta -o result_compleasm -t 64 -l mammalia -L result_compleasm
[results]summary.txt
## lineage: mammalia_odb10
S:97.91%, 9033
D:1.00%, 92
F:0.05%, 5
I:0.00%, 0
M:1.04%, 96
N:9226

**Comment by huangnengCSU** [comment]
Hi @Jerry-is-a-mouse ,

Compleasm only supports one assembly as input. If you need to evaluate two assemblies, you have to run compleasm twice. Evaluating two assemblies in one command have the same computational cost as running compleasm twice to evaluate two assemblies separately.

**Comment by Jerry-bioinformatics** [comment]
@huangnengCSU Thank you for your in-time reply very much. So if I have two haplotype-genome(eg.primary contigs and alternate contigs, or, haplotype1 and haplotype2), I need to run compleasm twice to obtain the haplotype completeness?

**Comment by huangnengCSU** [comment]
@Jerry-is-a-mouse 

Yes, each run of compleasm only reports the completeness of the input assembly.

**Comment by Jerry-bioinformatics** [comment]
Thank you very much! Best wishes!
