### ISSUE TITLE
Error in lineage 

### ISSUE THREAD

**Issue by mohamadi** [huangnengCSU/compleasm#3]
Hi @huangnengCSU, I'm getting below error on `bacteria_odb10` since there is no `refseq_db.faa.gz`. Is there a way to fix?

```bash
$ compleasm.py download bacteria
...
Success download from https://busco-data.ezlab.org/v5/data/lineages/bacteria_odb10.2020-03-06.tar.gz
No refseq_db.faa.gz in lineage bacteria_odb10, this lineage cannot be used in compleasm! Lineage file has been deleted.
...
```

Thanks!

**Comment by huangnengCSU** [comment]
Hi @mohamadi ,
 Compleasm is not designed for bacterial and viruses, as you can see there is no `refseq_db.faa.gz` in the lineage of bacteria. For these species we recommend still using BUSCO.
Neng
