### ISSUE TITLE
whether compleasm can be used for the evaluation of cds or pep?

### ISSUE THREAD

**Issue by zhangwenda0518** [huangnengCSU/compleasm#4]
Hello, I would like to ask whether compleasm can be used for the evaluation of cds or pep after genome gene annotation.
What parameter options should I pay attention to?
Thanks！

**Comment by huangnengCSU** [comment]
Hi @zhangwenda0518 ,
Compleasm cannot be used to evaluate annotation and I suggest to use BUSCO protein mode for evaluating the gene annotation.
Best,
Neng
