### ISSUE TITLE
Protein IndexError: list index out of range

### ISSUE THREAD

**Issue by gotouerina** [huangnengCSU/compleasm#40]
Command: compleasm.py protein -p Minous.pep.fa  -l mammalia  -t 50 -o minous -L /home/106public/software/compleasm/mb_downloads 

Searching for hmmsearch in the path where compleasm.py is located
Searching for hmmsearch in the current execution path
Searching for hmmsearch in $PATH
Traceback (most recent call last):
  File "/home/106public/software/compleasm/compleasm.py", line 2715, in <module>
    main()
  File "/home/106public/software/compleasm/compleasm.py", line 2711, in main
    args.func(args)
  File "/home/106public/software/compleasm/compleasm.py", line 2512, in protein_fun
    pr.run()
  File "/home/106public/software/compleasm/compleasm.py", line 2276, in run
    query_name = line[3]
IndexError: list index out of range

**Comment by gotouerina** [comment]
I meet this problems several times, and what will cause this?

**Comment by huangnengCSU** [comment]
Hi,

The problem seems to occur during the parsing of the hmmsearch output. Please run the script I provided using `python compleasm.py` to identify which hmmsearch output file is problematic, and then display the contents of that file here.
[compleasm_Issue40.zip](https://github.com/user-attachments/files/17365086/compleasm_Issue40.zip)

**Comment by gotouerina** [comment]
Hi  I used the compleasm.py in your zip and this time found no error!

**Comment by gotouerina** [comment]
here is the log
Searching for hmmsearch in the path where compleasm.py is located
Searching for hmmsearch in the current execution path
Searching for hmmsearch in $PATH

S:89.50%, 8257
D:4.70%, 434
F:2.58%, 238
M:3.22%, 297
N:9226
