### ISSUE TITLE
"I" value

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [huangnengCSU/compleasm#9]
Pardon my ignorance, but what it the "I" value in the summary. Busco does not produce this.

Thanks,

**Comment by GuillaumeHolley** [comment]
I was just wondering the same while going through my results.

**Comment by huangnengCSU** [comment]
Hi @theo-allnutt-bioinformatics @GuillaumeHolley ,
Apologies for any confusion. We separated fragmented genes into two categories. "F" means a gene that only a portion is present in the assembly and the rest cannot be aligned. "I" represents a gene that can not be fully aligned to a single position in the assembly. A section of the gene aligns to one position while the remaining aligns to another position in the assembly.

Best,
Neng

**Comment by GuillaumeHolley** [comment]
Hi @huangnengCSU,

Thank you for the clarification, it is actually very useful to have this distinction!

Guillaume
